### ISSUE TITLE
Exemple :  ExampleMesFrObservationBodyWeight001.json

### ISSUE THREAD

**Issue by M-Priour** [ansforge/FIG-mesures-de-sante#22]
Pour identifier la cladimed, est-ce qu'il ne faudrait pas plutôt utiliser "urn:oid:1.2.250.1.213.2.65" à la place de le TRE Cladimed
Cf : https://interop.esante.gouv.fr/ig/fhir/mesures/3.0.0/Observation-ExampleMesFrObservationBodyWeight001.json.html

**Comment by nicolasArnoux** [comment]
Bien vu. Corrigé.
