### ISSUE TITLE
Coquille : http://www.interopsante.org/fhir/structuredefinition/observation/fr-obervation-interpretation

### ISSUE THREAD

**Issue by M-Priour** [ansforge/FIG-mesures-de-sante#24]
Il manque le un "s" dans http://www.interopsante.org/fhir/structuredefinition/observation/fr-obervation-interpretation
Cf : 
- https://interop.esante.gouv.fr/ig/fhir/mesures/3.0.0/StructureDefinition-mes-fr-observation-bp.html
- StructureDefinition-mes-fr-observation-body-temperature
- StructureDefinition-mes-fr-observation-body-weight
- StructureDefinition-mes-fr-observation-bodyheight

**Comment by nicolasArnoux** [comment]
C'est un héritage des profils Interop Santé.
Ce n'est pas de notre fait.
