### ISSUE TITLE
fr-core-obervation-interpretation vs  fr-obervation-interpretation'

### ISSUE THREAD

**Issue by M-Priour** [ansforge/FIG-mesures-de-sante#25]
Pourquoi dans observatio dans "mes-fr-observation-bp" ,on fait référence à "fr-core-obervation-interpretation" alors que dans les autres profiles ont fait référence) "fr-obervation-interpretation" ?
J'ai aussi l'impression qu'il manque le s dans "fr-core-obervation-interpretation"

**Comment by nicolasArnoux** [comment]
Tu fais référence au binding dans Interpretation.
Ce n'est pas de notre fait. C'est un binding créé par Interop Santé:
https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783560
